dist: bionic
language: node_js
cache:
  yarn: true
node_js:
  - 14
branches:
  except:
    - /^no-ci.*$/
before_install:
  - export TZ=Asia/Singapore
  - export NODE_OPTIONS=--max_old_space_size=8192
script:
  - yarn run format:ci
  - yarn run eslint
  - travis_wait 30 yarn run build
  - yarn run test-coveralls
