language: node_js
node_js:
  - 9
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
branches:
  except:
    - /^no-ci.*$/
script:
  - yarn format:ci
  - yarn build-css
  - yarn tslint -p .
  - yarn test-coveralls
