name: Run CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  TZ: Asia/Singapore
  NODE_OPTIONS: --max_old_space_size=8192
  GENERATE_SOURCEMAP: false

jobs:
  deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup repository
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
  lint:
    needs: deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commands: [tsc, 'format:ci', eslint, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup repository
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: JOBS=$(nproc) yarn install --frozen-lockfile
      - name: Run command
        run: yarn run ${{ matrix.commands }}
  coveralls:
    name: Check code coverage
    needs: [deps, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup repository
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: JOBS=$(nproc) yarn install --frozen-lockfile
      - name: Coveralls
        run: yarn run test-coveralls
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
